### ISSUE TITLE
irresponsible - Validator and delagators can bypass the unstaking cool down period

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-11-covalent-judging#68]
irresponsible

high

# Validator and delagators can bypass the unstaking cool down period

## Summary
Validator and delagators can bypass the unstaking cool down period
## Vulnerability Detail
When a validator is added in the `addValidator` function, its `disabledAtBlock` is set to 1 to show the validator has been added but not yet enabled. (enabled validators have a `disabledAtBlock` value of 0)
```solidity
    function addValidator(address validator, uint128 commissionRate) external onlyStakingManager whenNotPaused returns (uint256 id) {
        require(commissionRate < DIVIDER, "Rate must be less than 100%");
        require(validator != address(0), "Validator address is 0");
        Validator storage v = _validators[validatorsN]; // use current number of validators for the id of a new validator instance
        v._address = validator;
        v.exchangeRate = uint128(DIVIDER); // make it 1:1 initially
        v.commissionRate = commissionRate;
        v.disabledAtBlock = 1; // set it to 1 to indicate that the validator is disabled
```
The validator must now stake an amount >= `validatorEnableMinStake` then the stakingManager can enable the validator. The problem here is that the validator can call `unstake` while the validator has not yet been activated yet. This will add his his unstake request to the `unstakings` mapping and given how the code is writen, once the validator is active, the validator can instantly unstake any stakes given that he stakes more than the original stake.
```solidity
        uint128 coolDownEnd = uint128(v.disabledAtBlock != 0 ? v.disabledAtBlock : block.number);
        unchecked {
            coolDownEnd += (isValidator ? validatorCoolDown : delegatorCoolDown);
        }
        uint128 unstakeId = uint128(v.unstakings[msg.sender].length);
        v.unstakings[msg.sender].push(Unstaking(coolDownEnd, effectiveAmount));
        emit Unstaked(validatorId, msg.sender, effectiveAmount, unstakeId);
```
as we can see if `v.disabledAtBlock` != 0 then we set `coolDownEnd` to `v.disabledAtBlock` and if the validator has yet to be enabled once, this will be 1. next we add `validatorCoolDown` to `coolDownEnd`. Given that we added 1 to the validator cool down, we can be certain that the validator can unstake instantly, unless the `validatorCoolDown` is > the number of total block ever on the ethereum mainnet which is/ will not be the case. Now validator has an unstakings which can be unstaked at any time without waiting. The validator is then enabled by the `stakingManager`. Once the validator is activated by the staking manager, if the validator decides to stake more than `validatorEnableMinStake` (the original amount he staked), he can and these can be unstaked instantly given that he abused the bug to get a queued unstake in the Unstakings mapping.

## POC
1. validator is added by stakingManager but not yet enabled. disabledAtBlock is set to 1
2. validator or delegator queue and unstake before the validator is active to abuse disabledAtBlock being 1
3. cooldown is set to cooldown + 1. This will mean that the validator or delegator can essentially unstake instantly.
4. validator or delegator wait for the validator to be enabled. 
5. They can now unstake whenever they want, they can unstake after 1 reward if they want and they will not have to wait the cool down period.

___This exploit can also be done by the delegators to also bypass cool down period___
side note: i only included validators in the original report and forgot to add that delegators can also abuse this.

## Impact
Validators and delegators do not have to wait for cool down to unstake, allowing them to gain rewards without the implied risk of having to keep tokens staked past the cool down period.
## Code Snippet
https://github.com/sherlock-audit/2023-11-covalent/blob/218d4a583286fa0d3d4263151a927f6cc9465b62/cqt-staking/contracts/OperationalStaking.sol#L242-L257

https://github.com/sherlock-audit/2023-11-covalent/blob/218d4a583286fa0d3d4263151a927f6cc9465b62/cqt-staking/contracts/OperationalStaking.sol#L529-L537

https://github.com/sherlock-audit/2023-11-covalent/blob/218d4a583286fa0d3d4263151a927f6cc9465b62/cqt-staking/contracts/OperationalStaking.sol#L559-L572
## Tool used

Manual Review

## Recommendation
this is complicated, not sure how to accurately give a good recommendation. Would not want to give bad advice.

Duplicate of #78

**Comment by ArnieGod** [comment]
Escalate 

this issue should be de duped from issue #78 the root causes are completely different and I believe 78 is also invalid.

the only duplicate of this issue is #76 . And this issue should be upgraded to a valid high issue with 1 dupe.

This issue out of the entire contest is the only issue which allows a user to unstake whenever he wants. It is easy to reproduce this issue if we read this report. Making the chance of abuse of this bug high. The impact is also high and undermines the entire functionality of the protocol. 
According to sherlock docs
> Inflicts serious non-material losses (doesn't include contract simply not working).

This issue fits the description above perfectly which should make this issue a valid high. We are undermining the entire staking mechanism which is the main point of these contracts.


TLDR I believe this issue is clearly high as well should be de duped from 78 and should be an entirely new issue with only issue 76 as its dupe, since that issue has same root cause as this one.

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> this issue should be de duped from issue #78 the root causes are completely different and I believe 78 is also invalid.
> 
> the only duplicate of this issue is #76 . And this issue should be upgraded to a valid high issue with 1 dupe.
> 
> This issue out of the entire contest is the only issue which allows a user to unstake whenever he wants. It is easy to reproduce this issue if we read this report. Making the chance of abuse of this bug high. The impact is also high and undermines the entire functionality of the protocol. 
> According to sherlock docs
> > Inflicts serious non-material losses (doesn't include contract simply not working).
> 
> This issue fits the description above perfectly which should make this issue a valid high. We are undermining the entire staking mechanism which is the main point of these contracts.
> 
> 
> TLDR I believe this issue is clearly high as well should be de duped from 78 and should be an entirely new issue with only issue 76 as its dupe, since that issue has same root cause as this one.

You've deleted an escalation for this issue.

**Comment by ArnieGod** [comment]
Escalate 

this issue is a unique high issue and does not have any dupes.

This issue was wrongly duped with issue #78 which root cause is based on the function `redeemRewards` .
This issue does not mention or rely on the `redeemRewards` function at all.

Additionally this issue is unique, after skimming through the issues i have not been able to find 1 issue which describes the root cause described in this issue.

The issues likelihood is very high/ almost certain if we read the report.
Additionally this issue should be high because of the following:

sherlock docs
>Inflicts serious non-material losses (doesn't include contract simply not working).

As far as I can tell this issue is the only valid issue which allows instant unstaking of rewards and is not contingent with another function.

The ability to unstake instantly undermine the entire purpose of the protocol and the contracts, following sherlock's rules i believe this issue is high severity.

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> this issue

You've deleted an escalation for this issue.

**Comment by ArnieGod** [comment]
if the judge needs further explaining or context, i am happy to do so. I just hope the issue is judged correctly and fairly thanks.

**Comment by midori-fuse** [comment]
Escalate

This issue is incorrect. Step 5 of the PoC mentions:

> They can now unstake whenever they want, they can unstake after 1 reward if they want and they will not have to wait the cool down period.

[Non-enabled valdiators do not earn rewards](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L286-L291). Unstakings also do not accrue rewards at all, therefore there is also no damage if they don't get a lock-cooldown.

The only path for an unstaking to go back to earning rewards is through [`recoverUnstaking()`](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L542). This function creates a completely new stake based on the existing unstake amount, and therefore the new staking is also subject to a proper cooldown when unstaked. 

Therefore "unstake after 1 reward" still has to wait for the cooldown, and this issue is incorrect.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This issue is incorrect. Step 5 of the PoC mentions:
> 
> > They can now unstake whenever they want, they can unstake after 1 reward if they want and they will not have to wait the cool down period.
> 
> [Non-enabled valdiators do not earn rewards](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L286-L291). Unstakings also do not accrue rewards at all, therefore there is also no damage if they don't get a lock-cooldown.
> 
> The only path for an unstaking to go back to earning rewards is through [`recoverUnstaking()`](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L542). This function creates a completely new stake based on the existing unstake amount, and therefore the new staking is also subject to a proper cooldown when unstaked. 
> 
> Therefore "unstake after 1 reward" still has to wait for the cooldown, and this issue is incorrect.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ArnieSec** [comment]
@midori-fuse every validator must go through the same flow when getting added as a validator. This includes a `stakingManager` calling the function `addValidator` during this state the validator must stake greater than or equal to the minimum.
The validator should stake the maximum he is allowed in order to take full advantage of this bug.

```solidity
require(staked >= validatorEnableMinStake, "Validator is insufficiently staked");
```
once this happens the staking Manager can Enable validator. the validator can call unstake and before the `enableValidator` 
tx cofirms, he can now unstake all the tokens but not all, some have to stay inside because of the minimum required amount. So the validator calls unstake and his unstaking is pushed into v.unstakings. Here is where the bug happens, because when in the state where the vallidator is added this is the value of disableAtBlock

```solidity
v.disabledAtBlock = 1;
```
this value is used to calculate the unstaking time stamp.

```solidity
        uint128 coolDownEnd = uint128(v.disabledAtBlock != 0 ? v.disabledAtBlock : block.number);
```
since as i have show above that `disableAtBlock` is set to 1 during this state, when calculating coolDownEnd above in the unstake function we use v.disabledAtBlock which as we know is currently set to 1.

next below we add coolDownEnd which is 1 to the validator cooldown period.

```solidity
            coolDownEnd += (isValidator ? validatorCoolDown : delegatorCoolDown);
```

essentially now we have created an unstaking with a timestamp in the past, which means we can unstake instantly.

then the enableValidator tx confirms so the validator is now online and earning rewards. The validator still has his v.unstakings ready and can call `transferUnstakedOut` to claim from the v.unstakings. since the validator is online and reward distribution is based on share quantity. The validator is getting rewards with no risk, because as i have shown the validator can unstake whenever he wants.

**Comment by midori-fuse** [comment]
@ArnieGod Reward distribution is based on share quantity, yes, but [shares are already burned as soon as the validator/delegator calls `unstake()`](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L504-L517). 

`transferUnstakedOut()` also [does not burn any shares](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L559), further proving that shares were already burned prior. 

Therefore unstakings pending cooldown do not accrue rewards.

**Comment by ArnieSec** [comment]
@midori-fuse im confused i havent looked at the codebase my poc is messed up, my poc pertains to issue #78 , but what im describing is different. the difference is that when redeeming we dont have to wait for cooldowns. but when unstaking the reward we do. Thats what my main point was. After 1 reward we have the unstakings and call redeem. Then can withdraw the unstakings. 

heres my audit notes
```solidity
function _redeemRewards(uint128 validatorId, address beneficiary, uint128 amount) internal {
        require(validatorId < validatorsN, "Invalid validator");
        require(beneficiary != address(0x0), "Invalid beneficiary");
        Validator storage v = _validators[validatorId];
        Staking storage s = v.stakings[msg.sender];
        //@audit no wait for unstakings, validator can call redeemrewards to bypass unstake countdown.
```

**Comment by ArnieSec** [comment]
I see my blunder now. I mistakenly thought redeemed rewards were taken from unstakings instead of v.stakings 
@midori-fuse my fault you are right.

ill remove my escalation, and take the duplication as i see now why the judge has decided to add this issue as duplicate, while making some bad assumptions, i still think the report describes somewhat the behavior of #78

**Comment by ArnieSec** [comment]
> Escalate
> 
> This issue is incorrect. Step 5 of the PoC mentions:
> 
> > They can now unstake whenever they want, they can unstake after 1 reward if they want and they will not have to wait the cool down period.
> 
> [Non-enabled valdiators do not earn rewards](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L286-L291). Unstakings also do not accrue rewards at all, therefore there is also no damage if they don't get a lock-cooldown.
> 
> The only path for an unstaking to go back to earning rewards is through [`recoverUnstaking()`](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L542). This function creates a completely new stake based on the existing unstake amount, and therefore the new staking is also subject to a proper cooldown when unstaked.
> 
> Therefore "unstake after 1 reward" still has to wait for the cooldown, and this issue is incorrect.

Escalate 

while some assumptions are incorrect, i still think the main points of the report should keep this issue as valid duplicate of issue #78 

>Validators and delegators do not have to wait for cool down to unstake, allowing them to gain rewards without the implied risk of having to keep tokens staked past the cool down period.

this and the poc step 5. describe the issue present in report #78 .

**Comment by sherlock-admin** [comment]
> > Escalate
> > 
> > This issue is incorrect. Step 5 of the PoC mentions:
> > 
> > > They can now unstake whenever they want, they can unstake after 1 reward if they want and they will not have to wait the cool down period.
> > 
> > [Non-enabled valdiators do not earn rewards](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L286-L291). Unstakings also do not accrue rewards at all, therefore there is also no damage if they don't get a lock-cooldown.
> > 
> > The only path for an unstaking to go back to earning rewards is through [`recoverUnstaking()`](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L542). This function creates a completely new stake based on the existing unstake amount, and therefore the new staking is also subject to a proper cooldown when unstaked.
> > 
> > Therefore "unstake after 1 reward" still has to wait for the cooldown, and this issue is incorrect.
> 
> Escalate 
> 
> while some assumptions are incorrect, i still think the main points of the report should keep this issue as valid duplicate of issue #78 
> 
> >Validators and delegators do not have to wait for cool down to unstake, allowing them to gain rewards without the implied risk of having to keep tokens staked past the cool down period.
> 
> this and the poc step 5. describe the issue present in report #78 . 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by midori-fuse** [comment]
I would also like to request the Sherlock team to void Arnie's escalation (or at least not accept it), only if my escalation ends up rejected and Arnie is correct. Voiding it will also not hurt Arnie's ratio.

Arnie's escalation argument was just "this issue was correctly judged". Given the two escalations are opposite, the lead judge is caught in a situation where any escalation result will deduct their fixed pay.

For this reason I don't believe it's fair for the lead judge to have to deal with this. Please treat Arnie's escalation as a response to my own escalation and take it with full consideration, but not accept it on the technical side.

**Comment by nevillehuang** [comment]
@ArnieGod Can you provide me a coded PoC based on your **original** submission so I can cross-check your **vulnerability detail** section? Seems like your PoC is incorrect based on discussions above.

Apologize in advance, since I should have done so during the 7-day request PoC period but I missed it.

**Comment by ArnieSec** [comment]
@nevillehuang i messed up in this report, I accidentally mixed up the some of vulnerability details and poc with another audit tag/ issue i had. 

So i described 2 different things here. The poc part here is invalid.

The second part where i described this in the impact section and somewhat in the vulnerability section.

> Validators and delegators do not have to wait for cool down to unstake, allowing them to gain rewards without the implied risk of having to keep tokens staked past the cool down period.

And this is description of #78

> Alice and Bob still have the same number of shares, and have the same claim to future rewards.
However Bob's position has less risk compared to a normal delegator, since he can get all of his funds out anytime by calling redeemRewards, and does not have to wait a cooldown period.

It's almost an exact match with that report. 

I essentially mixed up 2 different reports and jumbled it up into 1 report. My mistake I'm not sure how Sherlock deals with 2 issues being described in 1 report but I'll take your decision. I should have been more alert when writing my reports :(

**Comment by nevillehuang** [comment]
@ArnieGod Agree, I think your issue can remain duplicated.

**Comment by Czar102** [comment]
The description provided should be sufficient to understand the core issue. For the future, I would recommend the Watson to be more careful when composing the report.

Planning to reject the escalation and leave the issue as is.

**Comment by midori-fuse** [comment]
Ultimately this report's validity is then up to the reader's understanding, therefore my judgement when reading this report is subjective to myself only, and was likely a result of my reaction against Arnie's original (deleted) escalation.

Hence I fully respect the decision.

**Comment by Czar102** [comment]
Result:
Medium
Duplicate of #78

@midori-fuse thank you for understanding. I appreciate you making sure the issue is judged correctly, including "a response" to the initial escalation.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [midori-fuse](https://github.com/sherlock-audit/2023-11-covalent-judging/issues/68/#issuecomment-1937963192): rejected
- [ArnieGod](https://github.com/sherlock-audit/2023-11-covalent-judging/issues/68/#issuecomment-1938060656): rejected
